### PR TITLE
Augur Community Report Update

### PR DESCRIPTION
**Pull request by cdolfi**
3/4 community reports. There needs to be time spent analyzing the code and figuring out how to make it repeatable for other use cases

### CODE REVIEW

**Comment by isabelizimm** [comment]
are these the notebooks using our augur instance/data, or just moving templates from the Augur community repo?

**Comment by cdolfi** [comment]
This templates are using our temporary augur instance provided to us by the augur team (ping me if you want the config its a new one) to use for EDA. This will be used while we wait for our permanent instance to hopefully be set up on a Operate First VM within the month. Right now this is just dummy data to play with while we are waiting. This is mostly the templates with some minor edits that I made to make it easier to work with (ie allowing to put in the repo name vs having to figure out the repo_id from another notebook)

**Comment by isabelizimm** [comment]
> This templates are using our temporary augur instance provided to us by the augur team (ping me if you want the config its a new one) to use for EDA. 
Sounds good! For templates, I think this is a good starting point. We can make issues/update the ones that already exist to have more specifics for each notebook

**Review by isabelizimm — APPROVED** [review]

**Review by JamesKunstle — APPROVED** [review]
I looked through these notebooks in broad strokes. I think that, as @isabelizimm said, these are really good starting points for templates, and that these can be refined further as needed.

**Pull request merged**
